// Generated by Selenium IDE
package edu.pitt.cs;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;

public class PittEduTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless=new");
    options.addArguments("--no-sandbox");
    options.addArguments("--disable-dev-shm-usage");
    driver = new ChromeDriver(options);
}
  @After
  public void tearDown() {
      if (driver != null) {
          driver.quit();
      }
  }

  @Test
  public void tEST1TITLE() {
    // Test name: TEST-1-TITLE
    // Step 1: Open homepage
    driver.get("https://www.pitt.edu/");
    // Step 2: Assert the page title
    assertThat(driver.getTitle(), is("Home | University of Pittsburgh"));
  }

  @Test
  public void tEST2LOGOEXISTS() {
    // Test name: TEST-2-LOGO-EXISTS
    driver.get("https://www.pitt.edu/");
    // Check if the Pitt logo exists
    List<WebElement> elements = driver.findElements(By.cssSelector("img[alt='University of Pittsburgh']"));
    assert(elements.size() > 0);
  }

  // @Test
  // public void tEST3LOGOIMAGE() {
  //   // Test name: TEST-3-LOGO-IMAGE
  //   driver.get("https://www.pitt.edu/");
  //   // Grab logo src
  //   WebElement element = driver.findElement(By.cssSelector("img[alt='University of Pittsburgh']"));
  //   String logo = element.getAttribute("src");
  //   // Store src in vars and check suffix
  //   vars.put("logo", logo);
  //   assertTrue(vars.get("logo").toString().endsWith("/sites/default/files/assets/pitt_shield_white-home.png"));
  // }

  @Test
  public void tEST4SCHOOLSSCI() {
    // Test name: TEST-4-SCHOOL-SCI
    driver.get("https://www.pitt.edu/");
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));

    // Click menu button
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button.nav_content_trigger"))).click();

    // Wait for school list to load
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("block-pitt-25-edu-collegesschools-2")));

    // Check the 3rd item text
    String text = driver.findElement(By.xpath("//*[@id='block-pitt-25-edu-collegesschools-2']/ul/li[3]")).getText();
    assertThat(text, is("Computing & Information"));
  }

//   @Test
//   public void tEST5SCHOOLSCOUNT() {
//     // Test name: TEST-5-SCHOOLS-COUNT
//     driver.get("https://www.pitt.edu/");
//     WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));

//     // Open dropdown menu
//     wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button.nav_content_trigger"))).click();

//     // Wait until visible
//     wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("block-pitt-25-edu-collegesschools-2")));

//     // Count <li> items in school list
//     List<WebElement> schools = driver.findElements(By.cssSelector("#block-pitt-25-edu-collegesschools-2 ul > li"));
//     assertEquals(16, schools.size());
//   }
    @Test
    public void tEST5SCHOOLSCOUNT() {
    driver.get("https://www.pitt.edu/");
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));

    // Open dropdown menu
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button.nav_content_trigger"))).click();

    // Wait until visible
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("block-pitt-25-edu-collegesschools-2")));

    // Assert li[16] is present
    WebElement li16 = driver.findElement(By.xpath("//*[@id='block-pitt-25-edu-collegesschools-2']/ul/li[16]"));
    assertTrue(li16.isDisplayed());

    // Assert li[17] is NOT present
    List<WebElement> li17 = driver.findElements(By.xpath("//*[@id='block-pitt-25-edu-collegesschools-2']/ul/li[17]"));
    assertEquals(0, li17.size());
    }

  @Test
  public void tEST6SEARCHCSC() {
    // Test name: TEST-6-SEARCH-CSC
    driver.get("https://www.pitt.edu/");
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));

    // Click search toggle
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button[aria-label='Toggle search']"))).click();

    // Type into search input
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("edit-keys"))).sendKeys("computer science club");

    // Click search button
    driver.findElement(By.cssSelector("input[data-drupal-selector='edit-submit']")).click();

    // Confirm CSC link appears
    WebElement link = wait.until(ExpectedConditions.presenceOfElementLocated(
      By.xpath("//a[@class='gs-title' and contains(., 'Student Organization Spotlight: Computer Science Club (CSC)')]")
    ));
    
    assertTrue(link.isDisplayed());
  }
}
